// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use serde::{Serialize, Deserialize};


#[derive(Debug)]
pub struct Categoria {
    pub id: i32,
    pub nome: String,
}

#[derive(Debug)]
pub struct Fornecedor {
    pub id: i32,
    pub cnpj: String,
    pub nome: String,
    pub email: Option<String>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Produto {
    pub id: i32,
    pub nome: String,
    pub preco: f64,
    pub categoria: Option<i32>,
    pub fornecedor: Option<i32>,
    pub descricao: Option<String>,
    pub foto: Option<String>,
    pub formato_imagem: Option<String>,
    pub data_criacao: Option<NaiveDateTime>,
}

#[derive(Debug)]
pub struct Unidademedida {
    pub id: i32,
    pub descricao: String,
    pub sigla: Option<String>,
}
